### ISSUE TITLE
openBrowser hangs when trying to run openChrome.applescript

### ISSUE THREAD

**Issue by jessegranger** [zanettin/react-dev-utils#3]
## The problem

Starting at:

https://github.com/zanettin/react-dev-utils/blob/master/openBrowser.js#L69

```
  const shouldTryOpenChromeWithAppleScript =
    process.platform === 'darwin' &&
    (typeof browser !== 'string' || browser === OSX_CHROME);
```

This condition will be true for almost all OSX users (having BROWSER set to something is the less-common/non-default case). It could be argued to be more-or-less correct this way if it didn't then set you up for the second part of the bug, starting at:

https://github.com/zanettin/react-dev-utils/blob/master/openBrowser.js#L77

```
  execSync('ps cax | grep "Google Chrome"');
  execSync('osascript openChrome.applescript "' + encodeURI(url) + '"', {
    cwd: __dirname,
    stdio: 'ignore',
  });
```

The first execSync() is checking for an existing process with the name "Google Chrome", but it ignores the result, so even if you don't have Chrome running (or even installed on the system), it will run `openChome.applescript`, which will hang forever waiting for a Chrome window to appear.

Because this hang is inside an `execSync()` it also blocks the JS event loop, and other code can't do things like process key inputs (to gracefully cancel), run timers (to recognize that it has timed out), etc.

## Suggested fix

The result of the first execSync should be checked.

An additional check should be added (perhaps inside the applescript part), to check that Chrome is executable (before calling `make new window`).

The applescript call should not use `execSync`, it should wait on a promise internally so the event loop isn't blocked.

**Comment by zanettin** [comment]
hello @jessegranger 
thx a lot for filing this issue. guess you wanted to create an issue over at the official create-react-app github page. this repo was just created during webpack4 migration which was completed by the CRA team a few months back.
 thanks and have a nice day 👍
